---
title: "1000 repitiion parsing file"
output: word_document
date: "2023-09-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(reshape2) 
library(dplyr)
# AUB, updated 2023-09-07 (849 repeats in 24 hr run time on zaratan)

#totalpopsize <- 849
totalpopsize <- 1000
#change the number of times a simulation was ran, change to 849 only for 10,000 population size

X10000 <- read_delim("/Users/abuzarbhatty/Downloads/100pop.csv", delim = "\t", escape_double = FALSE,  col_types = cols(cycle = col_character(),  count_p1 =   col_number(), count_p2 = col_number()),  trim_ws = TRUE) 

#loads desired file from workstation and sets up file to be parsed, have to specify file path for file to load

X10000binary <- X10000 %>% mutate_if(is.numeric, ~1 * (. != 0))
#changes all vaues that are > 0 to 1, this changes our problem to binary. So either you have a mutation or you don't

X10000binary$cycle<- as.character(X10000binary$cycle)
X10000binary$count_p1<- as.numeric(X10000binary$count_p1)
X10000binary$count_p2<- as.numeric(X10000binary$count_p2)
# sets up data to be parsed

X10000binary2 <- aggregate(x = X10000binary$count_p1, by = list(X10000binary$cycle), FUN = sum)
X10000binary3 <- aggregate(x = X10000binary$count_p2, by = list(X10000binary$cycle), FUN = sum)
# sums all 1000 instances of a cycle together. So now you have a measure of how many times a mutation showed up at the specific generation out of a 1000 instances

X10000binary2$group2 <- X10000binary3$x
X10000binary2$x <- ((X10000binary2$x)/totalpopsize)*100
X10000binary2$group2 <- ((X10000binary2$group2)/totalpopsize)*100
# gives the % chance of a mutation showing up after a 1000 runs

plot(X10000binary2$Group.1, X10000binary2$x, col = 2 , xlab = "ticks/generations", ylab = "% chance of mutation showing up", type = "p", pch=1, cex=0.1) 

plot(X10000binary2$Group.1, X10000binary2$group2, col = 4 , xlab = "ticks/generations", ylab = "% chance of mutation showing up", type = "p", pch=1, cex=0.1) 

# Open a jpg file
jpeg("chanceofmutationp100.jpg", width = 500, height = 500)
# 2. Create a plot
plot(X10000binary2$Group.1, X10000binary2$x, col = 2 , xlab = "ticks/generations", ylab = "% chance of mutation showing up", type = "p", pch=1, cex=0.1) 
# Close the pdf file
dev.off() 

# Open a jpg file
jpeg("chanceofmutationp200.jpg", width = 500, height = 500) 
# 2. Create a plot
plot(X10000binary2$Group.1, X10000binary2$group2, col = 4 , xlab = "ticks/generations", ylab = "% chance of mutation showing up", type = "p", pch=1, cex=0.1) 
# Close the pdf file
dev.off() 

```
